### PR TITLE
Use Azure Bicep 💪

### PR DESCRIPTION
**Pull request by MarcusFelling**
Converted ARM templates to Bicep. Part of this included removing the hard-coded use of canadacentral region, to align all resources to the same region as the resource group. Deployment failures will occur if existing, conflicting resources aren't cleaned up.

### CODE REVIEW

**Review by nishanil — APPROVED** [review]
Thanks for the Bicep implementation 👍 Looks good to me! 
Can you confirm if these steps were tested: https://github.com/microsoft/dotnet-podcasts/blob/main/Deploy-websites-services.md#step-by-step-guide-to-deploying-websites-and-services-to-azure ?

**Comment by jamesmontemagno** [comment]
@MarcusFelling just ping me when this is ready

**Comment by MarcusFelling** [comment]
> Thanks for the Bicep implementation 👍 Looks good to me! Can you confirm if these steps were tested: https://github.com/microsoft/dotnet-podcasts/blob/main/Deploy-websites-services.md#step-by-step-guide-to-deploying-websites-and-services-to-azure ?

@nishanil @jamesmontemagno  - Yes, I tested this in my forked repo using `East US` for all resources, by deploying everything from scratch in a new resource group. Conflicts could occur in production with existing resources that don't align with the templates (e.g. all resources not in the same region). In that case, manual cleanup may be necessary. I don't have access to the sub where prod resources live, but happy to help troubleshoot if necessary.

**Comment by MarcusFelling** [comment]
> Thanks for the Bicep implementation 👍 Looks good to me! Can you confirm if these steps were tested: https://github.com/microsoft/dotnet-podcasts/blob/main/Deploy-websites-services.md#step-by-step-guide-to-deploying-websites-and-services-to-azure ?

@nishanil @jamesmontemagno  - Yes, I tested this in my forked repo using `East US` for all resources, by deploying everything from scratch in a new resource group. Conflicts could occur in production with existing resources that don't align with the templates (e.g. all resources not in the same region). In that case, manual cleanup may be necessary. I don't have access to the sub where prod resources live, but happy to help troubleshoot if necessary.

**Pull request merged**
