### PR TITLE
Fix iOS Publish by using a regular net6 components library

### PR DESCRIPTION
**Pull request by eerhardt**
See https://github.com/dotnet/maui/issues/5400#issuecomment-1077517303 for analysis on why this change is necessary.

FYI - @jamesmontemagno

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Prob need to adjust https://github.com/microsoft/dotnet-podcasts/blob/main/src/MobileBlazor/mauiapp/NetPodsMauiBlazor.csproj#L64 as well

**Review by javiercn — APPROVED** [review]
Looks good to me provided my limited context.

**Comment by eerhardt** [comment]
> Prob need to adjust https://github.com/microsoft/dotnet-podcasts/blob/main/src/MobileBlazor/mauiapp/NetPodsMauiBlazor.csproj#L64 as well

Done!

**Comment by jamesmontemagno** [comment]
Let me test it out real quick and will merge

**Pull request merged**
