### PR TITLE
Feature/use flex layout listen later and listen together

### PR DESCRIPTION
**Pull request by migueBarrera**
Hello James. I am trying to use Flex layout. I have two issues. 
1: The scroll is not working, am I doing something wrong? 
2: Is it possible to group with FlexLayout? I tried one option but it doesn't calculate the height correctly (it's commented in the code).

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Hmmm... that looks correct. I will try to pull it down and look. @pureween @redth are you able to look at this? Who owns flexlayout? @davidortinau you are a pro at flexlayout...

@migueBarrera  do you have some screenshots?

**Comment by migueBarrera** [comment]
Apparently, the flexlayout wraps fine, but...

Issues 1: If I use a flexlayout inside a scrollview, the scroll does not work.
image
image

Issues 2: For grouping, I am not sure if it is possible or if it is an error in calculating the height.
image

**Comment by jamesmontemagno** [comment]
I am thinking it would be 2 different flexlayouts..


```
<ScrollView>
  <StackLayout>
    <Label Text=""/>
    <FlexLayout>
    </FlexLayout>
    <Label Text=""/>
    <FlexLayout>
    </FlexLayout>
  </StackLayout>
</ScrollView>
```

**Comment by migueBarrera** [comment]
Hi james. I have tried your proposal but not work fine.
I use a VerticalStackLayout but this is the result:
On Android:
Screenshot 2022-04-29 at 10 49 39

**Comment by jamesmontemagno** [comment]
I'll pull down the branch and look today :)

**Comment by migueBarrera** [comment]
Ohhh thank you so much! I've updated the branch with the latest changes right now!

**Comment by jamesmontemagno** [comment]
@migueBarrera  we should maybe try the community toolkit -> https://docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/

They have a UniformedItemLayout https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Layouts/UniformItemsLayoutPage.xaml

**Comment by migueBarrera** [comment]
@jamesmontemagno  I have tried the toolkit's control UniformItemsLayout. A simple implementation, like this:   

```
        <ScrollView>
            <toolkit:UniformItemsLayout
                MaxColumns="2"
                Margin="10,50,10,0"
                BindableLayout.ItemsSource="{Binding WhatsNewList}">
                <BindableLayout.ItemTemplate>
                    <DataTemplate>
                        <BoxView Color="Red" HeightRequest="150" WidthRequest="150" Margin="4"/>
                    </DataTemplate>
                </BindableLayout.ItemTemplate>
            </toolkit:UniformItemsLayout >
        </ScrollView>
```
I have the same problem as with FlexLayout => Scroll does not work.

**Comment by jamesmontemagno** [comment]
Hmmm @brminnick thoughts?

**Comment by migueBarrera** [comment]
https://github.com/dotnet/maui/issues/6881

**Comment by jamesmontemagno** [comment]
@migueBarrera  is this still an issue? does it need to be re-based?

**Pull request closed without merging**
