### PR TITLE
.NET 7!

### PR DESCRIPTION
**Pull request by jamesmontemagno**

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
If everyone can give it 1 more pass here then I think we will be good! whoa!

**Comment by MarcusFelling** [comment]
> If everyone can give it 1 more pass here then I think we will be good! whoa!

@jamesmontemagno - a couple of updates I made to get this deployed (it was silently failing in GHA):
- The new web app slot that was manually added in the portal for staging had to be added to the Bicep IaC, along with updating the runtime of the web app to .NET 7
- The GitHub Actions step to build the web project was updated to use .NET 7 SDK. Not sure why this (and Hub) aren't built and deployed as a container like the API project; maybe web apps didn't support containers when this was originally built....

Can you switch the slot to dev mode and see what the error is? I don't have access to these resources.

https://dotnetpodcasts-staging.azurewebsites.net/

**Comment by jamesmontemagno** [comment]
Yeah... so this issue is that we have new endpoints setup so everything is going to fail in staging or trying to push out a new front end. So for now the tests will fail here, but we should just do a new PR to fix it up later if that makes sense.

**Comment by jamesmontemagno** [comment]
Staging environment setup:

https://dotnetpodcasts-staging.azurewebsites.net/discover


with new apis! https://podcastapicastaging.blackgrass-9b5c5276.eastus.azurecontainerapps.io/swagger/index.html

**Pull request merged**
