### PR TITLE
Feature/resume episode

### PR DESCRIPTION
**Pull request by antborari**
The following functionality means that destroying the application saves the status of a podcast if an episode was playing. Later when you open the app, it will continue playing where it was going, showing the player.

There is a bug in lifecycle method Ondestroying from class Window=> https://github.com/dotnet/maui/issues/6993
Platforms affected: Android and iOS, not works simply OnDestroying method, not produce crash when destroy the app in this platforms.

Windows and Mac works fine.

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Instead of creating your own window could you just do:

```csharp
protected override Windows CreateWindow(IActivationState activationState)
{
    var w = base.CreateWindow(activationState);

    w.Destroyed += (s,e) =>
     {
        //do stuff
      };

return w;
}
```

**Comment by antborari** [comment]
I have tried it and it still won't run => window.Destroying has the same behaviour as the OnDestroying() method, I have extended the issue with the EventHandler.

**Comment by jamesmontemagno** [comment]
gotcha! @pureween what is the recommendation here on windows?

**Comment by pulimento** [comment]
Update: In the related MAUI issue, it is said that this issue is confirmed on the latest release. Will wait for some news regarding this: https://github.com/dotnet/maui/issues/6993

**Comment by jamesmontemagno** [comment]
Can I merge this @antborari ? is it alright even with the bugs

**Comment by antborari** [comment]
@jamesmontemagno of course ! I think it can be merged

**Pull request merged**
